[package]
name = "gossip-glomers"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
maelstrom-node = "0.1.6"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.135", features = ["raw_value"] }
tokio = "1.43.0"
